# Generated by Django 4.0.3 on 2022-04-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rental_id',
            new_name='reservation_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='rental_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
