# Generated by Django 4.0.3 on 2022-04-21 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_checking_reservation_checkin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='rental_name',
            new_name='rental_id',
        ),
    ]
