# Generated by Django 4.0.3 on 2022-04-22 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_reservation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='previous_reservation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 22, 11, 51, 12, 997526), null=True),
        ),
    ]
